# Generated by Django 5.2.1 on 2025-06-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this profile is approved to be shown on the site.', verbose_name='approved'),
        ),
    ]
